In [140]:
# importing required libraries.
import pandas as pd
import numpy as np
import csv
import sklearn
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [141]:
# uploading train and test data.
df = pd.read_csv("train.csv",delimiter=',', low_memory=False)
df1 = pd.read_csv("test.csv",delimiter=',', low_memory=False)
## Analyzing data for cleansing.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51490 entries, 0 to 51489
Data columns (total 42 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Report Number                   51490 non-null  object 
 1   Local Case Number               45037 non-null  object 
 2   Agency Name                     51490 non-null  object 
 3   ACRS Report Type                51490 non-null  object 
 4   Crash Date/Time                 51490 non-null  object 
 5   Route Type                      46522 non-null  object 
 6   Road Name                       46988 non-null  object 
 7   Cross-Street Type               46471 non-null  object 
 8   Cross-Street Name               46968 non-null  object 
 9   Off-Road Description            6950 non-null   object 
 10  Municipality                    7567 non-null   object 
 11  Related Non-Motorist            3648 non-null   object 
 12  Collision Type                  

In [142]:
df.nunique()

Report Number                      3256
Local Case Number                  1429
Agency Name                          10
ACRS Report Type                      3
Crash Date/Time                   39573
Route Type                           10
Road Name                          2226
Cross-Street Type                    10
Cross-Street Name                  4525
Off-Road Description               4017
Municipality                         20
Related Non-Motorist                 11
Collision Type                       18
Weather                              12
Surface Condition                    11
Light                                 8
Traffic Control                      11
Driver Substance Abuse               11
Non-Motorist Substance Abuse          9
Person ID                         49209
Injury Severity                       5
Circumstance                        139
Drivers License State                65
Vehicle ID                        49160
Vehicle Damage Extent                 7


In [143]:
a = df['Equipment Problems'].mode()
df['Equipment Problems'].fillna('a',inplace=True)

a = df1['Equipment Problems'].mode()
df1['Equipment Problems'].fillna('a',inplace=True)

In [144]:
df = df.drop(['Agency Name','Vehicle Make','Vehicle Model','Equipment Problems','Location','Report Number','Local Case Number','Road Name','Cross-Street Name','Off-Road Description','Person ID','Vehicle ID'],axis=1)
## Drop Columns where atleast 80% values are missing/NaN
df=df.dropna(thresh=len(df)*.8, axis='columns')
print(df.info())
df1 = df1.drop(['Location','Report Number','Local Case Number','Road Name','Cross-Street Name','Off-Road Description','Person ID','Vehicle ID'],axis=1)
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51490 entries, 0 to 51489
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   ACRS Report Type                51490 non-null  object 
 1   Crash Date/Time                 51490 non-null  object 
 2   Route Type                      46522 non-null  object 
 3   Cross-Street Type               46471 non-null  object 
 4   Collision Type                  51191 non-null  object 
 5   Weather                         47461 non-null  object 
 6   Surface Condition               45611 non-null  object 
 7   Light                           50786 non-null  object 
 8   Traffic Control                 43716 non-null  object 
 9   Driver Substance Abuse          42395 non-null  object 
 10  Injury Severity                 51490 non-null  object 
 11  Drivers License State           48962 non-null  object 
 12  Vehicle Damage Extent           

In [145]:
df1 = df1.drop(['Agency Name','Vehicle Make','Vehicle Model','Equipment Problems','Municipality','Related Non-Motorist','Non-Motorist Substance Abuse','Circumstance'],axis=1)

In [146]:
a = df['Route Type'].mode()
df['Route Type'].fillna('a',inplace=True)
a = df['Cross-Street Type'].mode()
df['Cross-Street Type'].fillna('a',inplace=True)
a = df['Collision Type'].mode()
df['Collision Type'].fillna('a',inplace=True)
a = df['Weather'].mode()
df['Weather'].fillna('a',inplace=True)
a = df['Surface Condition'].mode()
df['Surface Condition'].fillna('a',inplace=True)
a = df['Light'].mode()
df['Light'].fillna('a',inplace=True)
a = df['Traffic Control'].mode()
df['Traffic Control'].fillna('a',inplace=True)
a = df['Driver Substance Abuse'].mode()
df['Driver Substance Abuse'].fillna('a',inplace=True)
a = df['Drivers License State'].mode()
df['Drivers License State'].fillna('a',inplace=True)
a = df['Vehicle Damage Extent'].mode()
df['Vehicle Damage Extent'].fillna('a',inplace=True)
a = df['Vehicle First Impact Location'].mode()
df['Vehicle First Impact Location'].fillna('a',inplace=True)
a = df['Vehicle Second Impact Location'].mode()
df['Vehicle Second Impact Location'].fillna('a',inplace=True)
a = df['Vehicle Body Type'].mode()
df['Vehicle Body Type'].fillna('a',inplace=True)
a = df['Vehicle Movement'].mode()
df['Vehicle Movement'].fillna('a',inplace=True)
a = df['Vehicle Continuing Dir'].mode()
df['Vehicle Continuing Dir'].fillna('a',inplace=True)
a = df['Vehicle Going Dir'].mode()
df['Vehicle Going Dir'].fillna('a',inplace=True)

a = df1['Route Type'].mode()
df1['Route Type'].fillna('a',inplace=True)
a = df1['Cross-Street Type'].mode()
df1['Cross-Street Type'].fillna('a',inplace=True)
a = df1['Collision Type'].mode()
df1['Collision Type'].fillna('a',inplace=True)
a = df1['Weather'].mode()
df1['Weather'].fillna('a',inplace=True)
a = df1['Surface Condition'].mode()
df1['Surface Condition'].fillna('a',inplace=True)
a = df1['Light'].mode()
df1['Light'].fillna('a',inplace=True)
a = df1['Traffic Control'].mode()
df1['Traffic Control'].fillna('a',inplace=True)
a = df1['Driver Substance Abuse'].mode()
df1['Driver Substance Abuse'].fillna('a',inplace=True)
a = df1['Drivers License State'].mode()
df1['Drivers License State'].fillna('a',inplace=True)
a = df1['Vehicle Damage Extent'].mode()
df1['Vehicle Damage Extent'].fillna('a',inplace=True)
a = df1['Vehicle First Impact Location'].mode()
df1['Vehicle First Impact Location'].fillna('a',inplace=True)
a = df1['Vehicle Second Impact Location'].mode()
df1['Vehicle Second Impact Location'].fillna('a',inplace=True)
a = df1['Vehicle Body Type'].mode()
df1['Vehicle Body Type'].fillna('a',inplace=True)
a = df1['Vehicle Movement'].mode()
df1['Vehicle Movement'].fillna('a',inplace=True)
a = df1['Vehicle Continuing Dir'].mode()
df1['Vehicle Continuing Dir'].fillna('a',inplace=True)
a = df1['Vehicle Going Dir'].mode()
df1['Vehicle Going Dir'].fillna('a',inplace=True)



In [147]:

print(df.info())
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51490 entries, 0 to 51489
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   ACRS Report Type                51490 non-null  object 
 1   Crash Date/Time                 51490 non-null  object 
 2   Route Type                      51490 non-null  object 
 3   Cross-Street Type               51490 non-null  object 
 4   Collision Type                  51490 non-null  object 
 5   Weather                         51490 non-null  object 
 6   Surface Condition               51490 non-null  object 
 7   Light                           51490 non-null  object 
 8   Traffic Control                 51490 non-null  object 
 9   Driver Substance Abuse          51490 non-null  object 
 10  Injury Severity                 51490 non-null  object 
 11  Drivers License State           51490 non-null  object 
 12  Vehicle Damage Extent           

In [148]:
data = ['ACRS Report Type','Route Type','Cross-Street Type','Collision Type','Weather','Surface Condition','Light','Traffic Control','Driver Substance Abuse','Injury Severity','Drivers License State','Vehicle Damage Extent','Vehicle First Impact Location','Vehicle Body Type','Vehicle Movement','Vehicle Continuing Dir','Vehicle Going Dir','Speed Limit','Driverless Vehicle','Parked Vehicle']
for i in data:
  print(df[i].value_counts(),'\n\n\n',df1[i].value_counts(),'\n\n---------------------------------------------------------------------------\n\n')

Property Damage Crash    31660
Injury Crash             18978
Fatal Crash                852
Name: ACRS Report Type, dtype: int64 


 Property Damage Crash    48193
Injury Crash             28927
Fatal Crash                115
Name: ACRS Report Type, dtype: int64 

---------------------------------------------------------------------------


Maryland (State)        22482
County                  16059
a                        4968
Municipality             2840
US (State)               2291
Interstate (State)       1145
Other Public Roadway      489
Ramp                      398
Government                390
Service Road              218
Unknown                   210
Name: Route Type, dtype: int64 


 Maryland (State)        34744
County                  24957
a                        7467
Municipality             4208
US (State)               3262
Interstate (State)       1455
Other Public Roadway      524
Government                315
Ramp                      268
Service Road         

In [149]:
df['Crash Date/Time'] = pd.to_datetime(df['Crash Date/Time'])
data = [df]
for i in data:
    i['Year'] = i['Crash Date/Time'].dt.year
    i['Month'] = i['Crash Date/Time'].dt.month
    i['Date'] = i['Crash Date/Time'].dt.day
    i['Day of Week'] = i['Crash Date/Time'].dt.dayofweek
    i['Hour'] = i['Crash Date/Time'].dt.hour

df1['Crash Date/Time'] = pd.to_datetime(df1['Crash Date/Time'])
data1 = [df1]
for i in data1:
    i['Year'] = i['Crash Date/Time'].dt.year
    i['Month'] = i['Crash Date/Time'].dt.month
    i['Date'] = i['Crash Date/Time'].dt.day
    i['Day of Week'] = i['Crash Date/Time'].dt.dayofweek
    i['Hour'] = i['Crash Date/Time'].dt.hour

In [150]:
df['Vehicle Year'] = df['Year']-df['Vehicle Year']
df.drop(['Year'],axis=1)
df.head()

ACRS Report Type     Crash Date/Time  ... Day of Week Hour
0           Injury Crash 2017-06-05 16:27:00  ...           0   16
1           Injury Crash 2020-02-22 10:00:00  ...           5   10
2  Property Damage Crash 2017-06-11 08:21:00  ...           6    8
3           Injury Crash 2019-05-10 07:30:00  ...           4    7
4           Injury Crash 2016-08-02 17:00:00  ...           1   17

[5 rows x 31 columns]

In [151]:
df = df.drop(['Crash Date/Time','Drivers License State'],axis=1)
df1 = df1.drop(['Crash Date/Time','Drivers License State'],axis=1)

In [152]:
df = pd.get_dummies(df, columns = ['ACRS Report Type','Route Type','Vehicle Second Impact Location','Cross-Street Type','Collision Type','Weather','Surface Condition','Light','Traffic Control','Driver Substance Abuse','Injury Severity','Vehicle Damage Extent','Vehicle First Impact Location','Vehicle Body Type','Vehicle Movement','Vehicle Continuing Dir','Vehicle Going Dir','Speed Limit','Driverless Vehicle','Parked Vehicle'])
df1 = pd.get_dummies(df1, columns = ['ACRS Report Type','Route Type','Vehicle Second Impact Location','Cross-Street Type','Collision Type','Weather','Surface Condition','Light','Traffic Control','Driver Substance Abuse','Injury Severity','Vehicle Damage Extent','Vehicle First Impact Location','Vehicle Body Type','Vehicle Movement','Vehicle Continuing Dir','Vehicle Going Dir','Speed Limit','Driverless Vehicle','Parked Vehicle'])


In [153]:
df.head()

Vehicle Year   Latitude  ...  Parked Vehicle_No  Parked Vehicle_Yes
0            12  39.263378  ...                  1                   0
1             2  39.068913  ...                  0                   1
2             1  38.993578  ...                  1                   0
3            18  39.083480  ...                  1                   0
4             3  38.996942  ...                  1                   0

[5 rows x 243 columns]

In [154]:
x_train, x_val= train_test_split( df, test_size=0.2, random_state=42)

In [155]:
X_train = x_train.iloc[:,x_train.columns!='Fault']
y_train = x_train['Fault'].values
X_val = x_val.iloc[:,x_val.columns!='Fault']
y_val = x_val['Fault'].values
X_test = df1
X_test = X_test.iloc[:,X_test.columns!='Id']

In [157]:
'''
# Scale data before applying PCA
scaling=StandardScaler()
 
# Use fit and transform method
scaling.fit(X_train)
Scaled_data=scaling.transform(X_train)
scaling.fit(X_val)
Scaled_data2=scaling.transform(X_val)
scaling.fit(X_test)
Scaled_data1=scaling.transform(X_test)
# Set the n_components=25
principal=PCA(n_components=150)
principal.fit(Scaled_data)
X_train=principal.transform(Scaled_data)
principal.fit(Scaled_data1)
X_test=principal.transform(Scaled_data1)
principal.fit(Scaled_data2)
X_val=principal.transform(Scaled_data2)
# Check the dimensions of data after PCA
#print(x.shape,x1.shape)'''

'\n# Scale data before applying PCA\nscaling=StandardScaler()\n \n# Use fit and transform method\nscaling.fit(X_train)\nScaled_data=scaling.transform(X_train)\nscaling.fit(X_val)\nScaled_data2=scaling.transform(X_val)\nscaling.fit(X_test)\nScaled_data1=scaling.transform(X_test)\n# Set the n_components=25\nprincipal=PCA(n_components=150)\nprincipal.fit(Scaled_data)\nX_train=principal.transform(Scaled_data)\nprincipal.fit(Scaled_data1)\nX_test=principal.transform(Scaled_data1)\nprincipal.fit(Scaled_data2)\nX_val=principal.transform(Scaled_data2)\n# Check the dimensions of data after PCA\n#print(x.shape,x1.shape)'

In [158]:
'''enc = OrdinalEncoder()
X_train = enc.fit_transform(X_train)
X_val = enc.fit_transform(X_val)
X_test = enc.fit_transform(X_test)'''

'enc = OrdinalEncoder()\nX_train = enc.fit_transform(X_train)\nX_val = enc.fit_transform(X_val)\nX_test = enc.fit_transform(X_test)'

In [159]:
'''smote = SMOTE(sampling_strategy='auto')

X_train, y_train = smote.fit_sample(X_train,y_train) 
X_val, y_val = smote.fit_sample(X_val,y_val) '''

"smote = SMOTE(sampling_strategy='auto')\n\nX_train, y_train = smote.fit_sample(X_train,y_train) \nX_val, y_val = smote.fit_sample(X_val,y_val) "

In [160]:
# fit model on training data
model1 = GradientBoostingClassifier(n_estimators=100, learning_rate=0.23, max_depth=5, random_state=0)
model1.fit(X_train, y_train)
y_pred_val = model1.predict(X_val)
print(y_pred_val)

[1 0 1 ... 1 0 1]


In [161]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_pred_val)

0.8539522237327637

In [162]:
# predicting on test data
y_pred1 = model1.predict(X_test)
print(y_pred1)

[1 0 1 ... 0 1 1]


In [164]:
# build the lightgbm model
import lightgbm as lgb
model2 = lgb.LGBMClassifier(boosting_type='dart')
model2.fit(X_train, y_train)
y_pred_val = model2.predict(X_val)
print(y_pred_val)
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_pred_val)

[1 0 1 ... 1 0 1]


0.8526898426879006

In [165]:
# predicting on test data
y_pred2 = model2.predict(X_test)
print(y_pred2)

[1 0 0 ... 0 1 1]


In [ ]:
submission = pd.DataFrame()
submission['Id'] = df1['Id']
submission['Fault'] = y_pred.reshape((y_pred.shape[0]))
submission.to_csv('sub_lgb3.csv', index=False)

In [166]:
# XGBClassifier
# fit model on training data
model3 = XGBClassifier(n_estimators=200, learning_rate=0.23, max_depth=5, random_state=0)
model3.fit(X_train, y_train)
y_pred_val = model3.predict(X_val)
print(y_pred_val)

[1 0 1 ... 1 0 1]


In [167]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_pred_val)

0.8548261798407458

In [168]:
# predicting on test data
y_pred3 = model3.predict(X_test)
print(y_pred3)

[1 0 0 ... 0 1 1]


In [131]:
from sklearn.ensemble import RandomForestClassifier
model4 = RandomForestClassifier(n_estimators = 100)
model4.fit(X_train, y_train)
y_pred_val = model4.predict(X_val)

In [132]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_pred_val)

0.8531753738590018

In [133]:
# predicting on test data
y_pred4 = model4.predict(X_test)
print(y_pred4)

[1 0 1 ... 0 1 1]


In [ ]:
submission = pd.DataFrame()
submission['Id'] = df1['Id']
submission['Fault'] = y_pred.reshape((y_pred.shape[0]))
submission.to_csv('sub_xg3.csv', index=False)

In [ ]:

'''# import libraries
import category_encoders as ce

# Define catboost encoder
cbe_encoder = ce.cat_boost.CatBoostEncoder()
  
# Fit encoder and transform the features
cbe_encoder.fit(X_train, y_train)
X_train1 = cbe_encoder.transform(X_train)
cbe_encoder.fit(X_val, y_val)
X_val1 = cbe_encoder.transform(X_val)'''

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [172]:
## CATBOOST
categorical_features_indices = np.where(type(X_train)!= np.float )[0]
#importing library and building model
from catboost import CatBoostClassifier
model5=CatBoostClassifier(iterations=300, depth=6, learning_rate=0.23)
model5.fit(X_train, y_train,cat_features=categorical_features_indices,eval_set=(X_val, y_val),plot=True)
y_pred_val = np.abs(np.round(model5.predict(X_val))).astype(int)
print(y_pred_val)
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_pred_val)


MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.5694629	test: 0.5690982	best: 0.5690982 (0)	total: 44.5ms	remaining: 13.3s
1:	learn: 0.5044713	test: 0.5035856	best: 0.5035856 (1)	total: 86.5ms	remaining: 12.9s
2:	learn: 0.4694263	test: 0.4689189	best: 0.4689189 (2)	total: 130ms	remaining: 12.8s
3:	learn: 0.4452888	test: 0.4450754	best: 0.4450754 (3)	total: 173ms	remaining: 12.8s
4:	learn: 0.4295761	test: 0.4294427	best: 0.4294427 (4)	total: 217ms	remaining: 12.8s
5:	learn: 0.4146310	test: 0.4141218	best: 0.4141218 (5)	total: 264ms	remaining: 12.9s
6:	learn: 0.4054106	test: 0.4055502	best: 0.4055502 (6)	total: 310ms	remaining: 13s
7:	learn: 0.3995083	test: 0.3995235	best: 0.3995235 (7)	total: 357ms	remaining: 13s
8:	learn: 0.3937030	test: 0.3938884	best: 0.3938884 (8)	total: 400ms	remaining: 12.9s
9:	learn: 0.3892642	test: 0.3893312	best: 0.3893312 (9)	total: 441ms	remaining: 12.8s
10:	learn: 0.3850323	test: 0.3853637	best: 0.3853637 (10)	total: 489ms	remaining: 12.8s
11:	learn: 0.3818689	test: 0.3822442	best: 0.3822442 (

0.8601670227228588

In [173]:
# predicting on test data
y_pred5 = np.round(np.abs(model5.predict(X_test))).astype(int)
print(y_pred5)

[1 0 0 ... 0 1 1]


In [175]:
y_pred = np.round((y_pred1+y_pred2+y_pred4+y_pred3+y_pred5)/5).astype(int)
print(y_pred)

[1 0 0 ... 0 1 1]


In [138]:
submission = pd.DataFrame()
submission['Id'] = df1['Id']
submission['Fault'] = y_pred.reshape((y_pred.shape[0]))
submission.to_csv('sub_cat13.csv', index=False)